#!/usr/bin/env python3
"""Regenerate src/pymantic/uri_schemes.py from the IANA URI scheme registry.

Run this when IANA adds schemes and pymantic's list has fallen behind:

    python scripts/update_uri_schemes.py

PrefixMap.resolve warns when it takes a value with an undeclared prefix as
an absolute IRI whose scheme isn't in this list, which usually means a
mistyped prefix. The list only drives that warning; resolution ignores it.

The registry is fetched as XML, the machine-readable form of
https://www.iana.org/assignments/uri-schemes/uri-schemes.txt. Every status
(Permanent, Provisional, Historical) is included.
"""

import argparse
from pathlib import Path
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET

REGISTRY_URL = "https://www.iana.org/assignments/uri-schemes/uri-schemes.xml"
MODULE_PATH = Path(__file__).resolve().parent.parent / "src/pymantic/uri_schemes.py"

NS = {"iana": "http://www.iana.org/assignments"}

# RFC 3986 section 3.1 scheme syntax.
SCHEME_SYNTAX = re.compile(r"[A-Za-z][A-Za-z0-9+.-]*")


def fetch_registry(url):
    with urllib.request.urlopen(url) as response:
        return ET.fromstring(response.read())


def scheme_names(registry):
    """Return the registered scheme names, lowercased, sorted and
    deduplicated. Schemes are case-insensitive (RFC 3986 section 3.1).

    The XML also carries the 'ipn' sub-registries, so only records in the
    uri-schemes-1 registry are read. The registry annotates some names in
    place, e.g. "shttp (OBSOLETE)", so only the leading token is kept. Any
    name that still isn't valid scheme syntax stops the script rather than
    being silently dropped.
    """
    schemes = registry.find("iana:registry[@id='uri-schemes-1']", NS)
    if schemes is None:
        sys.exit("error: no uri-schemes-1 registry found in the IANA XML")
    names = set()
    invalid = []
    for value in schemes.iterfind("iana:record/iana:value", NS):
        name = value.text.split(" ", 1)[0]
        if SCHEME_SYNTAX.fullmatch(name):
            names.add(name.lower())
        else:
            invalid.append(value.text)
    if invalid:
        sys.exit(f"error: registry entries with unexpected scheme syntax: {invalid}")
    return sorted(names)


def render_module(names, last_updated):
    lines = [
        f'"""A complete list of URI schemes registered with IANA as of {last_updated},',
        "lowercased. PrefixMap.resolve warns about an IRI whose scheme isn't one.",
        "",
        "Generated by scripts/update_uri_schemes.py; do not edit by hand.",
        '"""',
        "",
        "schemes = frozenset(",
        "    {",
        *(f'        "{name}",' for name in names),
        "    }",
        ")",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.parse_args()

    registry = fetch_registry(REGISTRY_URL)
    last_updated = registry.findtext("iana:updated", namespaces=NS)
    if not last_updated:
        sys.exit("error: no <updated> date found in the IANA XML")
    names = scheme_names(registry)

    old = MODULE_PATH.read_text() if MODULE_PATH.exists() else ""
    old_names = set(re.findall(r'^ +"([^"]+)",$', old, re.MULTILINE))
    MODULE_PATH.write_text(render_module(names, last_updated))

    added = sorted(set(names) - old_names)
    removed = sorted(old_names - set(names))
    print(
        f"wrote {len(names)} schemes to {MODULE_PATH} (registry updated {last_updated})"
    )
    print(f"added {len(added)}: {' '.join(added)}")
    print(f"removed {len(removed)}: {' '.join(removed) or '-'}")


if __name__ == "__main__":
    main()
